version: "3.0"
services:
  client:
    container_name: client
    build: ./client
    tty: true
    cap_add:
      - NET_ADMIN
  server:
    container_name: server
    build: .
    tty: true
    cap_add:
      - NET_ADMIN
    ports:
      - "8080:8080"
      - "80:80"
      - "443:443"
    # sysctls:
    #   net.core.rmem_max: 2500000
    # volumes:
    #   - /switching-http/letsencrypt:/etc/letsencrypt/
